dog_breeds = {
    "Affenpinscher", "Afghan Hound", "Aidi", "Airedale Terrier", "Akbash", "Akita", "Akita Inu",
    "Alano Español", "Alaskan Klee Kai", "Alaskan Malamute", "American Bulldog", "American Cocker Spaniel",
    "American Eskimo Dog", "American Foxhound", "American Hairless Terrier", "American Leopard Hound",
    "American Pit Bull Terrier", "American Staffordshire Terrier", "American Water Spaniel", "Anatolian Shepherd Dog",
    "Appenzeller Sennenhund", "Argentine Dogo", "Ariegeois", "Armant", "Australian Cattle Dog", "Australian Kelpie",
    "Australian Shepherd", "Australian Stumpy Tail Cattle Dog", "Australian Terrier", "Austrian Pinscher",
    "Azawakh", "Bakharwal Dog", "Barbet", "Basenji", "Basque Shepherd Dog", "Basset Artésien Normand",
    "Basset Bleu de Gascogne", "Basset Fauve de Bretagne", "Basset Hound", "Bavarian Mountain Hound", "Beagle",
    "Bearded Collie", "Beauceron", "Bedlington Terrier", "Belgian Laekenois", "Belgian Malinois", "Belgian Sheepdog",
    "Belgian Tervuren", "Bergamasco Sheepdog", "Berger Picard", "Bernese Mountain Dog", "Bichon Frise",
    "Biewer Terrier", "Black and Tan Coonhound", "Black Norwegian Elkhound", "Black Russian Terrier", "Bloodhound",
    "Blue Lacy", "Blue Picardy Spaniel", "Bluetick Coonhound", "Boerboel", "Bohemian Shepherd", "Bolognese",
    "Border Collie", "Border Terrier", "Borzoi", "Bosnian Coarse-haired Hound", "Boston Terrier", "Bouvier des Flandres",
    "Boxer", "Boykin Spaniel", "Bracco Italiano", "Braque d'Auvergne", "Braque du Bourbonnais", "Braque Francais",
    "Briard", "Brittany Spaniel", "Broholmer", "Bruno Jura Hound", "Brussels Griffon", "Bull Terrier", "Bullmastiff",
    "Bully Kutta", "Cairn Terrier", "Canaan Dog", "Canadian Eskimo Dog", "Cane Corso", "Cardigan Welsh Corgi",
    "Carolina Dog", "Carpathian Shepherd Dog", "Catahoula Leopard Dog", "Caucasian Shepherd Dog", "Cavalier King Charles Spaniel",
    "Central Asian Shepherd Dog", "Cesky Fousek", "Cesky Terrier", "Chesapeake Bay Retriever", "Chihuahua",
    "Chinese Chongqing Dog", "Chinese Crested", "Chinese Imperial Dog", "Chinese Shar-Pei", "Chinook", "Chippiparai",
    "Chow Chow", "Cimarrón Uruguayo", "Cirneco dell'Etna", "Clumber Spaniel", "Cockapoo", "Cocker Spaniel",
    "Collie", "Coton de Tulear", "Croatian Sheepdog", "Curly-Coated Retriever", "Czechoslovakian Wolfdog", "Dachshund",
    "Dalmatian", "Dandie Dinmont Terrier", "Danish-Swedish Farmdog", "Deutsche Bracke", "Doberman Pinscher",
    "Dogo Argentino", "Dogo Guatemalteco", "Dogue de Bordeaux", "Drentse Patrijshond", "Drever", "Dunker",
    "Dutch Shepherd", "Dutch Smoushond", "East Siberian Laika", "Elo", "English Bulldog", "English Cocker Spaniel",
    "English Foxhound", "English Pointer", "English Setter", "English Springer Spaniel", "English Toy Terrier",
    "Entlebucher Mountain Dog", "Epagneul Bleu de Picardie", "Estonian Hound", "Estrela Mountain Dog", "Eurasier",
    "Field Spaniel", "Fila Brasileiro", "Finnish Hound", "Finnish Lapphund", "Finnish Spitz", "Flat-Coated Retriever",
    "French Bulldog", "French Spaniel", "Galgo Español", "Gascon Saintongeois", "German Longhaired Pointer",
    "German Pinscher", "German Shepherd Dog", "German Shorthaired Pointer", "German Spitz", "German Wirehaired Pointer",
    "Giant Schnauzer", "Glen of Imaal Terrier", "Golden Retriever", "Goldendoodle", "Gordon Setter", "Grand Basset Griffon Vendéen",
    "Great Dane", "Great Pyrenees", "Greater Swiss Mountain Dog", "Greek Harehound", "Greenland Dog", "Greyhound",
    "Griffon Bleu de Gascogne", "Griffon Bruxellois", "Griffon Fauve de Bretagne", "Griffon Nivernais", "Hamiltonstovare",
    "Hanoverian Scenthound", "Harrier", "Havanese", "Hokkaido", "Hovawart", "Hungarian Greyhound", "Huntaway",
    "Ibizan Hound", "Icelandic Sheepdog", "Indian Pariah Dog", "Irish Red and White Setter", "Irish Setter",
    "Irish Terrier", "Irish Water Spaniel", "Irish Wolfhound", "Istrian Coarse-haired Hound", "Italian Greyhound",
    "Jack Russell Terrier", "Jagdterrier", "Japanese Akitainu", "Japanese Chin", "Japanese Spitz", "Japanese Terrier",
    "Jindo", "Kai Ken", "Kangal Shepherd Dog", "Kanni", "Karelian Bear Dog", "Karakachan Dog", "Keeshond", "Kerry Blue Terrier",
    "King Charles Spaniel", "Kishu Ken", "Komondor", "Kooikerhondje", "Koolie", "Korean Jindo", "Kromfohrländer",
    "Kuvasz", "Labrador Husky", "Labrador Retriever", "Lagotto Romagnolo", "Lakeland Terrier", "Lancashire Heeler",
    "Landseer", "Lapponian Herder", "Large Münsterländer", "Leonberger", "Lhasa Apso", "Lithuanian Hound",
    "Löwchen", "Maltese", "Manchester Terrier", "Maremma Sheepdog", "Mastiff", "McNab Dog", "Mexican Hairless Dog",
    "Miniature American Shepherd", "Miniature Bull Terrier", "Miniature Pinscher", "Miniature Schnauzer",
    "Mioritic Shepherd Dog", "Molossus", "Montenegrin Mountain Hound", "Moscow Watchdog", "Mudi", "Mudhol Hound",
    "Neapolitan Mastiff", "New Guinea Singing Dog", "Newfoundland", "Norfolk Spaniel", "Norfolk Terrier",
    "Norrbottenspets", "Northern Inuit Dog", "Norwegian Buhund", "Norwegian Elkhound", "Norwegian Lundehund",
    "Norwich Terrier", "Nova Scotia Duck Tolling Retriever", "Old Danish Pointer", "Old English Sheepdog",
    "Olde English Bulldogge", "Otterhound", "Pachón Navarro", "Papillon", "Parson Russell Terrier", "Patterdale Terrier",
    "Pekingese", "Pembroke Welsh Corgi", "Perro de Presa Canario", "Perro de Presa Mallorquin", "Peruvian Hairless Dog",
    "Petit Basset Griffon Vendéen", "Pharaoh Hound", "Phu Quoc Ridgeback", "Picardy Spaniel", "Plott Hound",
    "Podenco Canario", "Pointer", "Polish Greyhound", "Polish Hound", "Polish Lowland Sheepdog", "Polish Tatra Sheepdog",
    "Pomeranian", "Pont-Audemer Spaniel", "Poodle", "Porcelaine", "Portuguese Podengo", "Portuguese Pointer",
    "Portuguese Sheepdog", "Portuguese Water Dog", "Posavac Hound", "Prazsky Krysarik", "Pudelpointer", "Pug",
    "Puli", "Pumi", "Pyrenean Mastiff", "Pyrenean Shepherd", "Rafeiro do Alentejo", "Rajapalayam", "Rampur Greyhound",
    "Rat Terrier", "Redbone Coonhound", "Rhodesian Ridgeback", "Romanian Mioritic Shepherd Dog", "Rottweiler",
    "Russian Spaniel", "Russian Toy", "Russian Tsvetnaya Bolonka", "Russo-European Laika", "Saarloos Wolfdog",
    "Sabueso Español", "Saint Bernard", "Saint Hubert Jura Hound", "Saint Miguel Cattle Dog", "Saluki", "Samoyed",
    "Sarplaninac", "Schapendoes", "Schipperke", "Schweizer Laufhund", "Schweizerischer Niederlaufhund", "Scotch Collie",
    "Scottish Deerhound", "Scottish Terrier", "Sealyham Terrier", "Segugio Italiano", "Seppala Siberian Sleddog",
    "Serbian Hound", "Serbian Tricolour Hound", "Shar Pei", "Shetland Sheepdog", "Shiba Inu", "Shih Tzu", "Shikoku",
    "Shiloh Shepherd", "Siberian Husky", "Silken Windhound", "Silky Terrier", "Skye Terrier", "Sloughi",
    "Slovakian Wirehaired Pointer", "Slovenský Cuvac", "Slovenský Kopov", "Small Münsterländer", "Soft-Coated Wheaten Terrier",
    "South Russian Ovcharka", "Spanish Mastiff", "Spanish Water Dog", "Spinone Italiano", "Stabyhoun", "Staffordshire Bull Terrier",
    "Standard Schnauzer", "Styrian Coarse-haired Hound", "Sussex Spaniel", "Swedish Lapphund", "Swedish Vallhund",
    "Taiwan Dog", "Tamaskan Dog", "Teddy Roosevelt Terrier", "Telomian", "Tenterfield Terrier", "Thai Bangkaew Dog",
    "Thai Ridgeback", "Tibetan Kyi Apso", "Tibetan Mastiff", "Tibetan Spaniel", "Tibetan Terrier", "Tornjak",
    "Tosa Inu", "Toy Fox Terrier", "Toy Manchester Terrier", "Transylvanian Hound", "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound", "Tyrolean Hound", "Vizsla", "Volpino Italiano", "Weimaraner", "Welsh Corgi",
    "Welsh Sheepdog", "Welsh Springer Spaniel", "Welsh Terrier", "West Highland White Terrier", "West Siberian Laika",
    "Westphalian Dachsbracke", "Wetterhoun", "Whippet", "White Swiss Shepherd Dog", "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla", "Xoloitzcuintli", "Yakutian Laika", "Yorkshire Terrier", "Yugoslavian Mountain Hound",
    "Yugoslavian Shepherd Dog"
};